const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const elements=new Map(),storage=new Map(),events={};
function el(id){if(!elements.has(id)){const classes=new Set();elements.set(id,{id,style:{},children:[],textContent:'',classList:{add:k=>classes.add(k),remove:k=>classes.delete(k),contains:k=>classes.has(k),toggle:(k,v)=>v?classes.add(k):classes.delete(k)},appendChild(b){this.children.push(b)},set innerHTML(v){this.children=[]},get innerHTML(){return ''},addEventListener(){},removeAttribute(){},getContext:()=>new Proxy({createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})})})}return elements.get(id)}
const sandbox={console,document:{getElementById:el,createElement:()=>el('el'+Math.random()),addEventListener:(k,f)=>events[k]=f},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},innerWidth:390,innerHeight:844,devicePixelRatio:2,addEventListener:(k,f)=>events[k]=f,setTimeout:()=>0,requestAnimationFrame:()=>0,performance:{now:()=>0},Math};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('public/junja-survival-20261007.js','utf8'),sandbox);const run=s=>vm.runInContext(s,sandbox);
run('startGame();draw();drawItems()');assert.equal(run('run'),true);
run('keys.d=true;joy.active=true;joy.x=1;gainXp(500)');assert.equal(run('run'),false);assert.equal(run('joy.active'),false);assert.equal(run('!!keys.d'),false);let pending=run('pendingLevels');assert.ok(pending>1);for(let i=0;i<pending;i++)el('choices').children[0].onclick();assert.equal(run('pendingLevels'),0);assert.equal(run('run'),true);
run('togglePause();update(1)');assert.equal(run('paused'),true);const t=run('t');run('update(1)');assert.equal(run('t'),t);run('togglePause()');assert.equal(run('run'),true);
run('reset();wave=15;enemy();enemies[0].hp=0;t=19*18;spawn=100;update(.016)');assert.equal(run('finished'),false,'old boss must not clear final wave');while(run('pendingLevels'))el('choices').children[0].onclick();run('wave=20;enemy();enemies.find(e=>e.bossWave===20).hp=0;update(.016)');assert.equal(run('finished'),true);assert.equal(run('profile.runs'),1);run('end(true)');assert.equal(run('profile.runs'),1,'end is idempotent');
run('reset();enemies=[{x:100,y:100,r:14},{x:100,y:100,r:14}];separateEnemies()');assert.ok(run('Math.hypot(enemies[0].x-enemies[1].x,enemies[0].y-enemies[1].y)')>0);
run('reset();items=[{x:-100,y:9999,type:"heart",life:2,bob:0}];player.x=30;player.y=H-90;hp=50;collectItems(.016)');assert.equal(run('hp'),70);
run('reset();shot(player,player,10,"cyan")');assert.ok(run('shots.every(s=>Number.isFinite(s.vx)&&Number.isFinite(s.vy))'));
// Accelerated logic stress: game clock only, not human play or browser performance.
const stats=[];for(const [width,height] of [[390,844],[844,390],[1366,768]]){sandbox.innerWidth=width;sandbox.innerHeight=height;run('resize()');for(let round=0;round<3;round++){run(`reset();skills.nova.lvl=3;skills.chain.lvl=3;skills.orbit.lvl=3;`);let peak=0;for(let frame=0;frame<24000;frame++){run('hp=maxHp;player.inv=1;update(1/60)');if(run('pendingLevels')){while(run('pendingLevels'))el('choices').children[0].onclick()}if(frame%60===0){run('draw();drawItems()');assert.ok(run('enemies.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.y))'));peak=Math.max(peak,run('enemies.length'));assert.ok(peak<=57)}if(run('finished'))break}stats.push({width,height,peak,finalWave:run('wave'),finished:run('finished')})}}
console.log('SURVIVAL_LOGIC_OK',JSON.stringify(stats));
